### PR TITLE
Enhance tracing middleware

### PR DESCRIPTION
**Pull request by philipgian**
This PR does three things:
* Adds extra information on the Spans created using Opentracing's server-side tags.
* Creates the infrastructure for custom hooks to be called when a Span is created or finished.
* Fixes various PEP8 errors.

### CODE REVIEW

**Comment by tanner-bruce** [comment]
This looks good

**Comment by bhs** [comment]
@philipgian @tanner-bruce I am embarrassed by the insane delay here, but I'm only now seeing this PR. It's in a conflicted state, but if you can resolve those and add some sort of basic test coverage, I would be happy to merge in the functionality.

Thanks.

**Comment by SEJeff** [comment]
FYI @bhs I've fixed the conflicts in this PR and posted it as #21. I'm no a maintainer, so I can't simply push the fix to @philipgian's fork.

**Comment by philipgian** [comment]
I had totally forgot about this PR. :(

Unfortunately I'm not currently actively involved in this so I am a bit out of context.
The conflict resolution in PR #21 do seem fine to me by just looking it, but I do not have a setup to test it. I can if you like push an updated PR with the conflicts resolved, but I cannot at the moment provide any tests.

**Comment by carlosalberto** [comment]
Closing this one as it is superseded by #21 

Feel free to re-open otherwise ;)

**Pull request closed without merging**
