### PR TITLE
update opentracing>=2.0,<2.3

### PR DESCRIPTION
**Pull request by maguowei**

### CODE REVIEW

**Comment by Jamim** [comment]
Related issue: #49

**Comment by jan25** [comment]
Thanks! Should we pin to <3 instead of <2.3 ?

Based on https://github.com/opentracing-contrib/python-flask/pull/34#issuecomment-498389822

**Comment by maguowei** [comment]
@jan25 #53

**Comment by bj00rn** [comment]
@jan25 can we get expect a release with this? pip complains when runnning with `jaeger_client` wich currently depends on opentracing > 2.1.

cheers!

**Pull request closed without merging**
