### PR TITLE
Packaging improvements

### PR DESCRIPTION
**Pull request by mikebryant**
- Use versioneer, so releasing will end up being as simple as tagging a version
- Releases may be done by tagging the repo (e.g. use the Github UI), and will automatically be deployed to Pypi

### CODE REVIEW

**Comment by bhs** [comment]
@mikebryant thanks! Have you tested this yet?

**Comment by mikebryant** [comment]
@bhs yup, I ran this on my fork with appropriate changes against test.pypi.org and it worked. (and this is the same basic model we use for our public python packages)

**Comment by bhs** [comment]
Sounds great! I think you should merge this. LGTM. (I'll let you manage the merging process at your discretion)

**Comment by mikebryant** [comment]
Hmm. I don't seem to have access to accept merge requests?

**Comment by bhs** [comment]
@mikebryant your invite is pending: https://github.com/opentracing-contrib/python-django/invitations

**Comment by mikebryant** [comment]
Oh derp, I missed the email notification. Thanks! :)

**Pull request merged**
